site_name: Devaz48
theme: 
  name: material
  icon:
    logo: material/cat 
  custom_dir: overrides
  palette:

    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Mode Otomatis

    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Mode Terang

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Mode Gelap

copyright: This Website Is Maintained by Devaz48
plugins: []
