site_name: Devaz48
theme:
  name: material
  icon:
    logo: material/cat 
  custom_dir: overrides
  palette:
 - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

copyright: This Website Is Maintained by Devaz48
plugins: []
